apiVersion: v2
name: exporter-discovery
description: Network scanner for Prometheus exporters with Kubernetes ScrapeConfig integration
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: Fabian Heib
    url: https://github.com/xonvanetta
