image:
  repository: ghcr.io/xonvanetta/exporter-discovery
  tag: 0.0.1
  pullPolicy: IfNotPresent

config:
  networks:
  # Example networks to scan:
   - "10.33.10.0/24"
  # - "10.33.51.0/24"
  interval: "60m"
  workers: 128
  # Optional per-module configuration:
  # modules:
  #   - name: "ipmi"
  #     scrapeInterval: "5m"
  #     scrapeTimeout: "30s"
  #   - name: "node"
  #     scrapeInterval: "1m"
  #     scrapeTimeout: "10s"

serviceAccount:
  create: true
  name: exporter-discovery

rbac:
  create: true

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
